export const members = [
  {
    id: 0,
    number: "S1",
    name: "Yoon SeoYeon",
    bday: "August 6, 2003",
    color: "#1e90ff",
    emoji: "🐶",
    picture: "s1.webp",
  },
  {
    id: 1,
    number: "S2",
    name: "Jeong HyeRin",
    bday: "April 12, 2007",
    color: "#9172EC",
    emoji: "🐱",
    picture: "s2.webp",
  },
  {
    id: 2,
    number: "S3",
    name: "Lee JiWoo",
    bday: "October 24, 2005",
    color: "#FAFA33",
    emoji: "🐻",
    picture: "s3.webp",
  },
  {
    id: 3,
    number: "S4",
    name: "Kim ChaeYeon",
    bday: "December 4, 2004",
    color: "#66CC33",
    emoji: "🍑",
    picture: "s4.webp",
  },
  {
    id: 4,
    number: "S5",
    name: "Kim YooYeon",
    bday: "February 9, 2001",
    color: "#EC118F",
    emoji: "🐰",
    picture: "s5.webp",
  },
  {
    id: 5,
    number: "S6",
    name: "Kim SooMin",
    bday: "October 3, 2007",
    color: "#EF98AA",
    emoji: "🐿️",
    picture: "s6.webp",
  },
  {
    id: 6,
    number: "S7",
    name: "Kim NaKyoung",
    bday: "October 13, 2002",
    color: "#5F9EA0",
    emoji: "🐈‍⬛",
    picture: "s7.webp",
  },
  {
    id: 7,
    number: "S8",
    name: "Gong YuBin",
    bday: "February 3, 2005",
    color: "#FFE4E1",
    emoji: "🐯",
    picture: "s8.webp",
  },
  {
    id: 8,
    number: "S9",
    name: "Kaede",
    bday: "December 20, 2005",
    color: "#FFCC33",
    emoji: "🍁",
    picture: "s9.webp",
  },
  {
    id: 9,
    number: "S10",
    name: "Seo DaHyun",
    bday: "January 8, 2003",
    color: "#FBA0E3",
    emoji: "🍒",
    picture: "s10.webp",
  },
  {
    id: 10,
    number: "S11",
    name: "Kotone",
    bday: "March 10, 2004",
    color: "#FFDF00",
    emoji: "🦭",
    picture: "s11.webp",
  },
  {
    id: 11,
    number: "S12",
    name: "Kwak YeonJi",
    bday: "January 8, 2008",
    color: "#4169E1",
    emoji: "🧸",
    picture: "s12.webp",
  },
  {
    id: 12,
    number: "S13",
    name: "Nien",
    bday: "June 2, 2003",
    color: "#FFA343",
    emoji: "🍓",
    picture: "s13.webp",
  },
  {
    id: 13,
    number: "S14",
    name: "Park SoHyun",
    bday: "October 13, 2002",
    color: "#1034A6",
    emoji: "🐺",
    picture: "s14.webp",
  },
  {
    id: 14,
    number: "S15",
    name: "Xinyu",
    bday: "March 25, 2002",
    color: "#C80815",
    emoji: "🦊",
    picture: "s15.webp",
  },
  {
    id: 15,
    number: "S16",
    name: "Mayu",
    bday: "March 12, 2002",
    color: "#FFA089",
    emoji: "🐇",
    picture: "s16.webp",
  },
  {
    id: 16,
    number: "S17",
    name: "Lynn",
    bday: "April 12, 2006",
    color: "#AB62B4",
    emoji: "🦈",
    picture: "s17.webp",
  },
  {
    id: 17,
    number: "S18",
    name: "JooBin",
    bday: "January 16, 2009",
    color: "#B7F54A",
    emoji: "🐣",
    picture: "s18.webp",
  },
  {
    id: 18,
    number: "S19",
    name: "Jeong HaYeon",
    bday: "August 1, 2007",
    color: "#52D9BB",
    emoji: "🦔",
    picture: "s19.webp",
  },
  {
    id: 19,
    number: "S20",
    name: "Park ShiOn",
    bday: "April 3, 2006",
    color: "#FF428A",
    emoji: "🍞",
    picture: "s20.webp",
  },
  {
    id: 20,
    number: "S21",
    name: "Kim ChaeWon",
    bday: "March 2, 2007",
    color: "#C7A3DF",
    emoji: "🎀",
    picture: "s21.webp",
  },
  {
    id: 21,
    number: "S22",
    name: "Sullin",
    bday: "November 30, 2006",
    color: "#7BBA8D",
    emoji: "☃️",
    picture: "s22.webp",
  },
  {
    id: 22,
    number: "S23",
    name: "SeoAh",
    bday: "June 11, 2010",
    color: "#CFF4FF",
    emoji: "☀️",
    picture: "s23.webp",
  },
  {
    id: 23,
    number: "S24",
    name: "JiYeon",
    bday: "February 13, 2004",
    color: "#FEAA61",
    emoji: "🦢",
    picture: "s24.webp",
  },
];
